### ISSUE TITLE
Component: breadcrumbs - wordpress integration

### ISSUE THREAD

**Issue by aaronhans** [cagov/ca-design-system-gutenberg-blocks#14]
The breadcrumbs component is a client side web component created specifically for cannabis. This ticket represents the required integration steps to integrate it into the wordpress environment. 

This may involve:
- Creation of breadcrumbs custom block to insert the web component
- Addition to the custom pattern used on internal pages

We do not expect there to be any author customizable features in this component. It should present the current breadcrumb values based on current page.

**Comment by chachasikes** [comment]
Update: 
We did a different approach for cannabis headless. Closing this issue. Whatever approach we do next will come from updates to the main plugin based on future work in another project.
