### ISSUE TITLE
Redirection handling

### ISSUE THREAD

**Issue by chachasikes** [cagov/ca-design-system-gutenberg-blocks#57]
Sort our redirection capabilities & decide on data structure desired by headless pipeline. 

See if we can expose redirection plugin data to headless in order to give a redirection UI to site admins from wordpress for additional redirects not accommodated by page renames. (Also check how redirection captures page slug renames)

Note: Aaron did some work on this already

**Comment by chachasikes** [comment]
Hey @aaronhans  - Can you update us on the status of this system? 
What tasks are remaining?

**Comment by aaronhans** [comment]
Completed:

- Script to create redirects on S3 runnable here https://github.com/cagov/cannabis.ca.gov/blob/f77faec75d1f2f58be5f06ed46e379c109355d2f/package.json#L9 this uses a redirect json file manually exported from the WordPress plugin and writes redirect files that work on S3. 

Remaining: 

- How should we move the set of redirects managed in WordPress to the frontend repo when it changes?
- The redirects get blown away by the normal deploy action so the redirect creation script should be run after every deploy targeting the appropriate bucket.

**Comment by aaronhans** [comment]
Open ticket assigned to @wrendo to help prioritize the how will we synch wordpress and git repo redirect set here: https://github.com/cagov/cagov-design-system-headless-wordpress/issues/3

**Comment by aaronhans** [comment]
depends on https://github.com/cagov/wordpress-to-github/issues/50

**Comment by chachasikes** [comment]
Is duplicate of #56 

Closing this one & keeping one main thread for redirects.
