### ISSUE TITLE
Lock down /users

### ISSUE THREAD

**Issue by chachasikes** [cagov/ca-design-system-gutenberg-blocks#65]
The users endpoint reveals user data by default. 

This was a recommended plugin to try to lock down the users page. https://wordpress.org/plugins/disable-json-api/ plugin

This change will impact wordpress to github (it should cause an error based on the current source code), and so we will need a fix for this to happen first: https://github.com/cagov/wordpress-to-github/issues/111

**Comment by chachasikes** [comment]
(Note: emails are not included by default)

**Comment by carterm** [comment]
Highly speculative. No evidence this is an issue.
